# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3
      - image: cypress/base:8
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    steps:
      - checkout
      - run: npm i -D enzyme
      - run: npm i -D react-test-renderer enzyme-adapter-react-16
      - run: npm install
      - run: apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      - run: cypress run # "run" job comes from "cypress" orb
      - run: npm test
  workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build'  # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
    # deploy:
    #   - add_ssh_keys:
    #       - fingerprints:
    #           - "xxx"
    #   - run: npm install --save-dev gh-pages
    #   - run: npm run build
    #   - run: npm run deploy
