# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3
      - image: cypress/base:8
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    steps:
      - checkout
      - run: npm i -D enzyme
      - run: npm i -D react-test-renderer enzyme-adapter-react-16
      - run: npm install
      - run: cypress/run # "run" job comes from "cypress" orb
      - run: npm test
      - run: cypress/run # "run" job comes from "cypress" orb
      #  - run: npx cypress run
    # deploy:
    #   - add_ssh_keys:
    #       - fingerprints:
    #           - "xxx"
    #   - run: npm install --save-dev gh-pages
    #   - run: npm run build
    #   - run: npm run deploy
